"""
TODO: This module outputs the synthetic data into the formats compatible with ..... 
"""
import networkx as nx
import datetime
import os
import csv
import shutil
import numpy as np

class GridExporter:
    """
    Exports the generated synthetic grid to standard file formats.
    
    1. MATPOWER (.m): 
       - Standard bridge for Pypowsybl (pypowsybl.network.load)
       - Supported by Pandapower (pandapower.converter.from_mpc)
       
    2. Pandapower CSVs (Folder):
       - Converts PU to Physical units (Ohms, kA) based on V_base=230kV.
       - Column names match pandapower.create_* parameters.
    """

    def __init__(self, graph: nx.Graph, base_mva: float = 100.0, base_kv: float = 230.0):
        self.graph = graph
        self.base_mva = base_mva
        self.base_kv = base_kv
        
        # Calculate Base Impedance for PU -> Ohm conversion
        # Z_base = V^2 / S
        self.z_base_ohm = (self.base_kv ** 2) / self.base_mva
        
        # Calculate Base Current for PU -> kA conversion
        # I_base = S / (sqrt(3) * V)
        self.i_base_ka = self.base_mva / (np.sqrt(3) * self.base_kv)

    def _get_matpower_header(self, case_name="SyntheticGrid") -> str:
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        return f"""function mpc = {case_name}
%MATPOWER Case file: {case_name}
%Generated by PowerGridSynthesizer on {timestamp}

mpc.version = '2';
mpc.baseMVA = {self.base_mva};
"""

    def export_to_matpower(self, filepath: str):
        """
        Saves the grid to a MATPOWER (.m) file.
        This is the preferred format for bridging with Pypowsybl.
        """
        os.makedirs(os.path.dirname(os.path.abspath(filepath)), exist_ok=True)
        
        # 1. Identify Slack Bus (Highest Capacity Gen)
        max_p = -1.0
        slack_bus = None
        for n, d in self.graph.nodes(data=True):
            if d.get('bus_type') == 'Gen':
                p_cap = d.get('pg_max', 0.0)
                if p_cap > max_p:
                    max_p = p_cap
                    slack_bus = n
        if slack_bus is None:
            slack_bus = list(self.graph.nodes())[0]

        # 2. Prepare Data Rows
        bus_rows = []
        gen_rows = []
        branch_rows = []
        
        node_mapping = {} 
        sorted_nodes = sorted(list(self.graph.nodes()))
        
        # BUS Data
        for i, n in enumerate(sorted_nodes):
            bus_id = i + 1
            node_mapping[n] = bus_id
            d = self.graph.nodes[n]
            b_type_str = d.get('bus_type', 'Conn')
            
            # MATPOWER Types: 1=PQ, 2=PV, 3=Ref
            if n == slack_bus: b_type = 3
            elif b_type_str == 'Gen': b_type = 2
            else: b_type = 1
                
            pd = d.get('pl', 0.0)
            # bus_i type Pd Qd Gs Bs area Vm Va baseKV zone Vmax Vmin
            row = f"\t{bus_id}\t{b_type}\t{pd:.2f}\t0.00\t0\t0\t1\t1.0\t0.0\t{self.base_kv}\t1\t1.1\t0.9;"
            bus_rows.append(row)
            
            # GEN Data
            if b_type_str == 'Gen':
                pg = d.get('pg', 0.0)
                pmax = d.get('pg_max', 0.0)
                # bus Pg Qg Qmax Qmin Vg mBase status Pmax Pmin ...
                gen_row = f"\t{bus_id}\t{pg:.2f}\t0.00\t999\t-999\t1.0\t{self.base_mva}\t1\t{pmax:.2f}\t0.00\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0\t0;"
                gen_rows.append(gen_row)

        # BRANCH Data
        for u, v, d in self.graph.edges(data=True):
            fbus = node_mapping[u]
            tbus = node_mapping[v]
            r = d.get('r', 0.0)
            x = d.get('x', 0.001)
            rate_a = d.get('capacity', 999.0) # MVA
            
            # fbus tbus r x b rateA rateB rateC ratio angle status angmin angmax
            branch_row = f"\t{fbus}\t{tbus}\t{r:.5f}\t{x:.5f}\t0.00000\t{rate_a:.2f}\t{rate_a:.2f}\t{rate_a:.2f}\t0\t0\t1\t-360\t360;"
            branch_rows.append(branch_row)

        # 3. Write File
        try:
            with open(filepath, 'w') as f:
                case_name = os.path.splitext(os.path.basename(filepath))[0]
                case_name = case_name.replace('-', '_').replace(' ', '_')
                f.write(self._get_matpower_header(case_name))
                
                f.write("\n%% bus data\nmpc.bus = [\n" + "\n".join(bus_rows) + "\n];\n")
                f.write("\n%% generator data\nmpc.gen = [\n" + "\n".join(gen_rows) + "\n];\n")
                f.write("\n%% branch data\nmpc.branch = [\n" + "\n".join(branch_rows) + "\n];\n")
                
            print(f"-> MATPOWER export success: {filepath}")
            return True
        except IOError as e:
            print(f"Error exporting to MATPOWER: {e}")
            return False

    def export_to_pandapower_csv(self, folder_path: str):
        """
        Exports CSVs with Physical Units (Ohm, kA) for Pandapower.
        """
        # Create/Clear directory
        if os.path.exists(folder_path):
            shutil.rmtree(folder_path)
        os.makedirs(folder_path)

        sorted_nodes = sorted(list(self.graph.nodes()))
        node_mapping = {n: i for i, n in enumerate(sorted_nodes)} # 0-based index for pandas often preferred

        # 1. bus.csv
        # Pandapower: name, vn_kv, type, zone, in_service
        with open(os.path.join(folder_path, 'bus.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['name', 'vn_kv', 'type', 'zone', 'in_service'])
            for n in sorted_nodes:
                d = self.graph.nodes[n]
                b_type = 'b' # busbar
                if d.get('bus_type') == 'Conn': b_type = 'n' # node
                writer.writerow([f"Bus {n}", self.base_kv, b_type, 1, True])

        # 2. load.csv
        # Pandapower: bus, p_mw, q_mvar, sn_mva, name, scaling, in_service
        with open(os.path.join(folder_path, 'load.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['bus', 'p_mw', 'q_mvar', 'sn_mva', 'name', 'scaling', 'in_service'])
            for n in sorted_nodes:
                d = self.graph.nodes[n]
                if d.get('bus_type') == 'Load' and d.get('pl', 0) > 0:
                    # 'bus' column in pandapower csv import usually expects the index or name depending on method.
                    # We assume index here for raw dataframe usage.
                    writer.writerow([node_mapping[n], d['pl'], 0.0, self.base_mva, f"Load {n}", 1.0, True])

        # 3. sgen.csv (Static Generators)
        # Pandapower: bus, p_mw, q_mvar, sn_mva, name, type, in_service
        with open(os.path.join(folder_path, 'sgen.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['bus', 'p_mw', 'q_mvar', 'sn_mva', 'name', 'type', 'in_service'])
            for n in sorted_nodes:
                d = self.graph.nodes[n]
                if d.get('bus_type') == 'Gen':
                    writer.writerow([node_mapping[n], d.get('pg', 0), 0.0, self.base_mva, f"Gen {n}", 'SGEN', True])

        # 4. line.csv
        # Pandapower: from_bus, to_bus, length_km, r_ohm_per_km, x_ohm_per_km, c_nf_per_km, max_i_ka, name, in_service
        with open(os.path.join(folder_path, 'line.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['from_bus', 'to_bus', 'length_km', 'r_ohm_per_km', 'x_ohm_per_km', 'c_nf_per_km', 'max_i_ka', 'name', 'in_service'])
            
            for u, v, d in self.graph.edges(data=True):
                # Convert PU to Physical
                r_ohm = d.get('r', 0.0) * self.z_base_ohm
                x_ohm = d.get('x', 0.001) * self.z_base_ohm
                
                # Capacity MVA to Max Current kA
                # I_max_ka = S_mva / (sqrt(3) * V_kv)
                cap_mva = d.get('capacity', 999.0)
                max_i_ka = cap_mva / (np.sqrt(3) * self.base_kv)
                
                writer.writerow([
                    node_mapping[u], 
                    node_mapping[v], 
                    1.0, # length_km (Dummy 1km so ohm_per_km == ohm total)
                    r_ohm, 
                    x_ohm, 
                    0.0, # c_nf
                    max_i_ka,
                    f"Line {u}-{v}", 
                    True
                ])
        
        print(f"-> Pandapower CSV export success: {folder_path}/")
        print(f"   (Physical units calculated with V_base={self.base_kv}kV, S_base={self.base_mva}MVA)")